# Generated by Django 4.1.3 on 2022-11-13 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='voter',
            unique_together={('user', 'election_address')},
        ),
    ]
