# Generated by Django 4.1.3 on 2022-11-14 05:25

import app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', app.models.UserManager()),
            ],
        ),
    ]
