# Generated by Django 4.1.3 on 2022-12-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_election'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='election',
            field=models.CharField(max_length=256),
        ),
    ]
